FORMAT: 1A
HOST: http://yourITASserver:4730/
VERSION: 1.04

# ITAS Client Services API 1.04

## Disclaimer

**** Warning: at this point, ITAS API does not support asynchronus or multithreading calls for POST, PUT and PATCH requests. Async or multithreading requests could result in various Error messages, or even a corruption of data in extreme cases and are therefore not supported. ****
<br />
<br />
<strong>Release notes</strong> (XX<sup>st</sup> XX 2019)

## New Endpoints

<ul>
<li>ITAS Data Modification Service <b>Create ITAS Data</b>: Create ITAS Data via mapped entities,<a href="/#reference/itas-data-modification-service/itas-data-modification-service/create-itas-data"> Link</a></li>
<li>ITAS Data Modification Service <b>Update ITAS Data</b>: Update ITAS Data via mapped entities,<a href="/#reference/itas-data-modification-service/itas-data-modification-service/update-itas-data"> Link</a></li>
<li>ITAS Data Modification Service <b>Delete ITAS Data</b>: Delete ITAS Data via mapped entities,<a href="/#reference/itas-data-modification-service/itas-data-modification-service/delete-itas-data"> Link</a></li>
</ul>

## Updated Endpoints

<ul>
    <li>None</li>
</ul>
<chandiv>** ends ** </div>

## AccessToken [/AT]
Model Header containing AccessToken

+ Model
    + Header

            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg



# Group Data Processing Services
### TBC

# Group DocMan

## Document Type Required Fields [/Docman/RequiredFields/{DocumentType}]
`GET` Required Fields for Document Type

### Read Required Fields [GET]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|Data|Array of Required Fields|`array`||||

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg


+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data (RequiredFields)
        + Response (200 SuccessResponse)

+ Response 404 (application/json)
    + Attributes (404 ResponseNoRec)


## Document Upload [/DocMan/Upload]
`POST` Upload Document, using request body type form-data, and optional model value to add indexing information

### Upload Document [POST]

<b>Request Body type 'Form-Data'</b>
|Key|Value|Constraint|
|--------|-----------|----|
|File|`Select Files`|Required|
|Model|Example: `{"TradingEntityId": "JT", "DocumentType": "INVOICES", "CounterpartyId": "ABCD.P", "ContractId": "P00001.000", "DocumentRef": "PI1900001", "WipAccount": "0001.000"}`||

<b>Response Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|DocmanDocumentId|Docman Document id|`number`||||

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data : (DocmanDocumentId)
        + Response (201 CreateResponse)

+ Response 400 (application/json)
    + Attributes (400 BadReadResponse)

+ Response 404 (application/json)
    + Attributes (404 NotFound)


## Document Indexing [/DocMan/Index]
`POST` Index Document

### Index Document [POST]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|<b>Request Body</b>||||||
|Name|Document Name|`string`|200|||
|TradingEntityId|Trading Entity ID|`string`|2|||
|DocumentType|Document Type|`string`|30|||
|CounterpartyId|Counterparty Id|`string`|10|||
|ContractId|Contract Id|`string`|10|||
|DocumentRef|Document Reference|`string`|9|||
|WIPAccountId|WIP Account Id|`string`|11|||
|PhysicalPath|Physical Path|`string`|200|||
|IsPhysicalPathEncrypted|Is Physical Path Encrypted|`boolean`||||


<b>Response Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|DocmanDocumentId|Docman Document id|`number`||||

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg


    + Attributes (IndexDocument)


+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data : (DocmanDocumentId)
        + Response (201 CreateResponse)

+ Response 400 (application/json)
    + Attributes (400 BadReadResponse)

+ Response 404 (application/json)
    + Attributes (404 NotFound)



## Download Document [/DocMan/Download/{CompanyDocumentsAndId}]
`GET` Download Document

### Download Document [GET]

<b>Query Parameters</b>
|Key|Value|Constraint|
|--------|-----------|----|
|Section|`CompanyDocuments`|Required|
|Id|Example: `12345`|Required|

<b>Response Body</b>
<br />
Streamed File Download

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg


+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Response (200 SuccessResponse)

+ Response 404 (application/json)
    + Attributes (404 ResponseNoRec)


## Document Archiving [/DocMan/Archive]
`PUT` Archive Document

### Archive Document [PUT]

<b>Request Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|<b>Request Body</b>||||||
|Path|Document Path|`string`|200|||


<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|Data|Data response|`string`||||

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg


    + Attributes (ArchiveDocument)


+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data : Document archived successfully (string)
        + Response (200 UpdateResponse)

+ Response 400 (application/json)
    + Attributes (400 BadReadResponse)

+ Response 404 (application/json)
    + Attributes (404 NotFound)


# Group ITAS Data Modification Service

## ITAS Data Modification Service [/Modification]
`POST` Create, Update and Delete Itas data via mapped entites
### Create ITAS Data [POST]

<b>Request Body</b>
<br />
See Example panel for an example request body


<b>Response Data</b>
<br />
See Example panel for the example response body

+ Request (text/plain)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Body
            mutation
                {
                    CreateDepartment(Input:
                    {
                        DepartmentId : "ABCD"
                        DepartmentDescription: "ABCD Dep"
                        CountryCode : "GB"
                        TradingEntityId : "JT"
                    })
                {
                    DepartmentId,
                    DepartmentDescription
                }
             }

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data (DepartmentCreate)
        + Response (200 SuccessResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 ResponseDQS)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 ResponseDQS)


### Update ITAS Data [POST]

<b>Request Body</b>
<br />
See Example panel for an example request body


<b>Response Data</b>
<br />
See Example panel for the example response body

+ Request (text/plain)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Body
        mutation
        {
            UpdateDepartment(Input:
            {
                DepartmentId : "ABCD"
                DepartmentDescription: "Department ABCD"
                TradingEntityId : "JT"
            })
            {
                DepartmentId,
                DepartmentDescription
            }
        }

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data (DepartmentUpdate)
        + Response (200 SuccessResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 ResponseDQS)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 ResponseDQS)

### Delete ITAS Data [POST]

<b>Request Body</b>
<br />
See Example panel for an example request body


<b>Response Data</b>
<br />
See Example panel for the example response body

+ Request (text/plain)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Body
        mutation
        {
            DeleteDepartment(Input:
            {
                DepartmentId : "ABCD"
                TradingEntityId : "JT"
            })
            {
                DepartmentId,
                DepartmentDescription
            }
        }

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data (DepartmentUpdate)
        + Response (200 SuccessResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 ResponseDQS)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 ResponseDQS)


# Group ITAS Data Query Service

## ITAS Data Query Service [/Query]
`POST` Query Itas data via mapped entites
### Query ITAS Data [POST]

<b>Request Body</b>
<br />
See Example panel for an example request body


<b>Response Data</b>
<br />
See Example panel for the example response body

+ Request (text/plain)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg


    + Body
        {
            Departments(TradingEntityIds : ["jt", "qa"], Top: 200, Skip: 100)
            {
                DepartmentId
                DepartmentDescription
                NominalCategory
                {
                    NominalCategoryId
                    NominalCategoryDescription
                    NominalGroup
                }
                Country
                {
                    CountryId
                    CountryDescription
                }
                EDICode
                Status
            }
        }

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data (array [DQSDepartments])
        + Response (200 SuccessResponse)
        + Pagination (Pagination)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 ResponseDQS)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 ResponseDQS)


# Group ITAS Messages
### TBC

# Group Key Value Pair Store
### TBC

# Group Reporting Data

##  Data Factory [/ReportingData/DataFactoryExport]
`POST` Schedule Data exports.  * <a href="/#introduction/disclaimer"> (Disclaimer)</a>
### Data Factory Export [POST]

<b>Request Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|Request|Request|`string`|||Required|

<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|JobRef|Job Reference|`string`||||



+ Request (application/json)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg


    + Attributes (DataFactoryExport)

+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data (JobId)
        + Response (201 CreateResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)


## Report Factory [/ReportingData/ReportFactoryExport]
`POST` Generate report through report factory.  * <a href="/#introduction/disclaimer"> (Disclaimer)</a>
### Report Factory Export [POST]

<b>Request Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|Request|Request|`string`|||Required|

<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|JobRef|Job Reference|`string`||||



+ Request (application/json)
    + Header

            AccessToken:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg


    + Attributes (ReportFactoryExport)

+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data (JobId)
        + Response (201 CreateResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)


# Group Valuation-Physical
Data endpoints for Trade Valuation

## Physical Trade Valuation Request [/Valuation/Physical/TradeValuationRequest]
`POST` Request for Valuation of Trades.

### Create Physical Trade Valuation Request [POST]

<b>Request Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|TradingEntityId|Trading Entity ID|`array`||||
|ContractType|Contract Type|`array`|||`P` or `S`|
|ContractStatus|Contract Status|`array`|||`O`, `C` or `Q`|
|ContractApproved|Contract Approved|`boolean`||||
|CounterpartyCode|Counterparty Code|`array`||||
|CommodityCodePart1|Commodity Code|`array`||||
|CommodityCodePart2|Commodity Origin|`array`||||
|CommodityCodePart3|Commodity Grade|`array`||||
|CommodityCodePart4|Commodity Code Section 4|`array`||||
|CommodityCodePart5|Commodity Code Section 5|`array`||||
|TraderCode|Trader Code|`array`||||
|DepartmentCode|Department Code|`array`||||
|PaymentTermCode|Payment Term Code|`array`||||
|ContractTermCode|Contract Term Code|`array`||||
|ContractTermPortCode|Contract Term Port Code|`array`||||
|ShipmentStatusCode|Shipment Status Code|`array`||||
|SingleCcyConVal|Single Currency Contract Value|`boolean`||||
|SingleCcyCosts|Single Currency Costs|`boolean`||||
|RateOfExchangeDate|Rate of Exchange Date|`number`||||
|TableExtension|Table Extension|`string`|9|||
|ValuationPeriod|Valuation Period|`array`||`Obsolete`||
|AppKey|Application Key|`string`||||
|IncludeFOPnLAndFOContractValuations|Include FO PnL and FO Contract Valuations|`boolean`||If set to `true`, this will increase processing time by 300%||

<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|RequestId|Request ID|`string`||||

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (PhysicalTradeValRequest)

+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data (PhysicalTradeValResponse)
        + Response (201 CreateResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)


## Physical Trade Valuation Trading Entity Request [/Valuation/{TradingEntityId}/Physical/TradeValuationTradingEntityRequest]
`POST` Request for Valuation of Trades for a single Trading Entity.

### Create Physical Trade Valuation Trading Entity Request [POST]

<b>Request Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractType|Contract Type|`array`|||`P` or `S`|
|ContractStatus|Contract Status|`array`|||`O`, `C` or `Q`|
|ContractApproved|Contract Approved|`boolean`||||
|CounterpartyCode|Counterparty Code|`array`||||
|CommodityCodePart1|Commodity Code|`array`||||
|CommodityCodePart2|Commodity Origin|`array`||||
|CommodityCodePart3|Commodity Grade|`array`||||
|CommodityCodePart4|Commodity Code Section 4|`array`||||
|CommodityCodePart5|Commodity Code Section 5|`array`||||
|TraderCode|Trader Code|`array`||||
|DepartmentCode|Department Code|`array`||||
|PaymentTermCode|Payment Term Code|`array`||||
|ContractTermCode|Contract Term Code|`array`||||
|ContractTermPortCode|Contract Term Port Code|`array`||||
|ShipmentStatusCode|Shipment Status Code|`array`||||
|SingleCcyConVal|Single Currency Contract Value|`boolean`||||
|SingleCcyCosts|Single Currency Costs|`boolean`||||
|RateOfExchangeDate|Rate of Exchange Date|`number`||||
|TableExtension|Table Extension|`string`|9|||
|ValuationPeriod|Valuation Period|`array`||`Obsolete`||
|AppKey|Application Key|`string`||||
|IncludeFOPnLAndFOContractValuations|Include FO PnL and FO Contract Valuations|`boolean`||If set to `true`, this will increase processing time by 300%||

<b>Response Data</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|RequestId|Request ID|`string`||||

+ Parameters
    + TradingEntityId (required, string, `JT`) ... Identify specific trading entity.

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

    + Attributes (PhysicalTradeValTradingEntityRequest)

+ Response 201 (application/json; charset=utf-8)
    + Attributes 
        + Data (PhysicalTradeValResponse)
        + Response (201 CreateResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

## Physical Trade Valuation Request Information [/Valuation/Physical/TradeValuationInfo/{RequestId}]
`GET` Information relating to the request of Physical Trade Valuation
### Read Physical Trade Valuation Request Information  [GET]
 
<b>Response Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|TradingEntityId|Trading Entity ID|`array`||||
|ContractType|Contract Type|`array`|||`P` or `S`|
|ContractStatus|Contract Status|`array`|||`O`, `C` or `Q`|
|ContractApproved|Contract Approved|`boolean`||||
|CounterpartyCode|Counterparty Code|`array`||||
|CommodityCodePart1|Commodity Code|`array`||||
|CommodityCodePart2|Commodity Origin|`array`||||
|CommodityCodePart3|Commodity Grade|`array`||||
|CommodityCodePart4|Commodity Code Section 4|`array`||||
|CommodityCodePart5|Commodity Code Section 5|`array`||||
|TraderCode|Trader Code|`array`||||
|DepartmentCode|Department Code|`array`||||
|PaymentTermCode|Payment Term Code|`array`||||
|ContractTermCode|Contract Term Code|`array`||||
|ContractTermPortCode|Contract Term Port Code|`array`||||
|ShipmentStatusCode|Shipment Status Code|`array`||||
|SingleCcyConVal|Single Currency Contract Value|`boolean`||||
|SingleCcyCosts|Single Currency Costs|`boolean`||||
|RateOfExchangeDate|Rate of Exchange Date|`number`||||
|TableExtension|Table Extension|`string`|9|||
|ValuationPeriod|Valuation Period|`array`||`Obsolete`||
|AppKey|Application Key|`string`||||
|IncludeFOPnLAndFOContractValuations|Include FO PnL and FO Contract Valuations|`boolean`||||


<b>Response Messages</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|RequestId|Request ID|`string`||||
|RequestTime|Request Time|`datetime`||||
|RequestStatus|Request Status|`string`||||
|RequestCompleteTime|Request Complete Time|`datetime`||||

+ Parameters
    + RequestId (required, string, `a123a456-7891-23a4-a567-8a9a10aaa123`) ... Identify specific request ID.

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data (PhysicalTradeValRequest)
        + Response (200 SuccessResponse)
        + Messages (array [ResultsMessageComplete])

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 BadReadResponse)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)


## Physical Trade Valuation Re-Request [/Valuation/Physical/TradeValuationReRequest/{RequestId}]
`PUT` Re-Submit Request for Valuation of Trades.
### Create Physical Trade Valuation Re-Request [PUT]
 
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|RequestId|Request ID|`string`|||Required|

+ Parameters
    + RequestId (required, string, `a123a456-7891-23a4-a567-8a9a10aaa123`) ... Identify specific request ID.

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg


+ Response 200 (application/json; charset=utf-8)
    + Attributes  
        + Data 
            + RequestId: `a123a456-7891-23a4-a567-8a9a10aaa123` (string)
        + Response (200 UpdateResponse)

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 Response)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)



## Physical Trades Valuation Results [/Valuation/Physical/TradeValuationResults/{RequestId}]
`GET` Trades Valuation Results from Request Query
### Physical Trades Valuation Results  [GET]

<b>Response Body</b> 
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|ContractId|Contract ID|`string`|10|||
|TradingEntityId|Trading Entity ID|`string`|2|||
|PnLCurrency|see <b><a href="/#reference/data-object-definitions/pnl-currency">PnL Currency</a></b> object|`object`||||
|ContractCurrency|see <b><a href="/#reference/data-object-definitions/contract-currency">Contract Currency</a></b> object|`object`||||
|FunctionalCurrency|see <b><a href="/#reference/data-object-definitions/functional-currency">Functional Currency</a></b> object|`object`|||

<b>Response Messages</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|RequestId|Request ID|`string`||||
|RequestTime|Request Time|`datetime`||||
|RequestStatus|Request Status|`string`||||
|RequestCompleteTime|Request Complete Time|`datetime`||||

+ Parameters
    + RequestId (required, string, `a123a456-7891-23a4-a567-8a9a10aaa123`) ... Identify specific request ID.

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data (array [PhysicalTradeValuesResults])
        + Pagination (Pagination)
        + Response (200 SuccessResponse)
        + Messages (array [ResultsMessageComplete])

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 BadReadResponse)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)

## Physical Trades Valuation Results Summary [/Valuation/Physical/TradeValuationSummary/{RequestId}]
`GET` Summary Valuations from Request Query
### Physical Trades Valuation Results Summary  [GET]

<b>Response Body</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|<b>CounterpartyList</b>||[array]||||
|CounterpartyCode|Counterparty Code|`string`|10|||
|PnLCurrency|see <b><a href="/#reference/data-object-definitions/pnl-currency">PnL Currency</a></b> object|[array] of `object`||||
|ContractCurrency|see <b><a href="/#reference/data-object-definitions/contract-currency">Contract Currency</a></b> object|[array] of `object`||||
|FunctionalCurrency|see <b><a href="/#reference/data-object-definitions/functional-currency">Functional Currency</a></b> object|[array] of `object`||||
|<b>CommodityList</b>||[array]|
|CommodityFullCode|`Composite Key` delimited by double pipe "&#124;&#124;"|`string`|50|Example <b><a href="/#reference/composite-key-examples/commodityfullcode">Composite Key</a></b>||
|PnLCurrency|see <b><a href="/#reference/data-object-definitions/pnl-currency">PnL Currency</a></b> object|[array] of `object`||||
|ContractCurrency|see <b><a href="/#reference/data-object-definitions/contract-currency">Contract Currency</a></b> object|[array] of `object`||||
|FunctionalCurrency|see <b><a href="/#reference/data-object-definitions/functional-currency">Functional Currency</a></b> object|[array] of `object`||||
|<b>TraderList</b>||[array]|
|TraderCode|Trader Code|`string`|3|||
|PnLCurrency|see <b><a href="/#reference/data-object-definitions/pnl-currency">PnL Currency</a></b> object|[array] of `object`||||
|ContractCurrency|see <b><a href="/#reference/data-object-definitions/contract-currency">Contract Currency</a></b> object|[array] of `object`||||
|FunctionalCurrency|see <b><a href="/#reference/data-object-definitions/functional-currency">Functional Currency</a></b> object|[array] of `object`||||
|<b>DepartmentList</b>||[array]|
|DepartmentCode|Department Code|`string`|4|||
|PnLCurrency|see <b><a href="/#reference/data-object-definitions/pnl-currency">PnL Currency</a></b> object|[array] of `object`||||
|ContractCurrency|see <b><a href="/#reference/data-object-definitions/contract-currency">Contract Currency</a></b> object|[array] of `object`||||
|FunctionalCurrency|see <b><a href="/#reference/data-object-definitions/functional-currency">Functional Currency</a></b> object|[array] of `object`||||
|<b>PaymentTermList</b>||[array]|
|PaymentTermCode|Payment Term Code|`string`|8|||
|PnLCurrency|see <b><a href="/#reference/data-object-definitions/pnl-currency">PnL Currency</a></b> object|[array] of `object`||||
|ContractCurrency|see <b><a href="/#reference/data-object-definitions/contract-currency">Contract Currency</a></b> object|[array] of `object`||||
|FunctionalCurrency|see <b><a href="/#reference/data-object-definitions/functional-currency">Functional Currency</a></b> object|[array] of `object`||||
|<b>ContractTermList</b>||[array]|
|ContractTermCode|Contract Term Code|`string`|8|||
|PnLCurrency|see <b><a href="/#reference/data-object-definitions/pnl-currency">PnL Currency</a></b> object|[array] of `object`||||
|ContractCurrency|see <b><a href="/#reference/data-object-definitions/contract-currency">Contract Currency</a></b> object|[array] of `object`||||
|FunctionalCurrency|see <b><a href="/#reference/data-object-definitions/functional-currency">Functional Currency</a></b> object|[array] of `object`||||
|<b>ContractTermPortList</b>||[array]|
|ContractTermPortCode|Contract Term Port Code|`string`|8|||
|PnLCurrency|see <b><a href="/#reference/data-object-definitions/pnl-currency">PnL Currency</a></b> object|[array] of `object`||||
|ContractCurrency|see <b><a href="/#reference/data-object-definitions/contract-currency">Contract Currency</a></b> object|[array] of `object`||||
|FunctionalCurrency|see <b><a href="/#reference/data-object-definitions/functional-currency">Functional Currency</a></b> object|[array] of `object`||||
|<b>ShipmentStatusList</b>||[array]|
|ShipmentStatusCode|Shipment Status Code|`string`|2|||
|PnLCurrency|see <b><a href="/#reference/data-object-definitions/pnl-currency">PnL Currency</a></b> object|[array] of `object`||||
|ContractCurrency|see <b><a href="/#reference/data-object-definitions/contract-currency">Contract Currency</a></b> object|[array] of `object`||||
|FunctionalCurrency|see <b><a href="/#reference/data-object-definitions/functional-currency">Functional Currency</a></b> object|[array] of `object`||||
|<b>TradingEntityList</b>||[array]|
|TradingEntityId|Trading Entity ID|`string`|2|||
|PnLCurrency|see <b><a href="/#reference/data-object-definitions/pnl-currency">PnL Currency</a></b> object|[array] of `object`||||
|ContractCurrency|see <b><a href="/#reference/data-object-definitions/contract-currency">Contract Currency</a></b> object|[array] of `object`||||
|FunctionalCurrency|see <b><a href="/#reference/data-object-definitions/functional-currency">Functional Currency</a></b> object|[array] of `object`||||

<b>Response Messages</b>
|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|RequestId|Request ID|`string`||||
|RequestTime|Request Time|`datetime`||||
|RequestStatus|Request Status|`string`||||

+ Parameters
    + RequestId (required, string, `a123a456-7891-23a4-a567-8a9a10aaa123`) ... Identify specific request ID.

+ Request (application/json)
    + Header

            AccessToken: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg

+ Response 200 (application/json; charset=utf-8)
    + Attributes 
        + Data (PhysicalTradeValuesResultsSum)
        + Response (200 SuccessResponse)
        + Messages (array [ResultsMessage])

+ Response 400 (application/json; charset=utf-8)
    + Attributes (400 BadReadResponse)

+ Response 404 (application/json; charset=utf-8)
    + Attributes (404 Response)


# Group Data Object Definitions
List of re-usable Data Objects referenced as `object` types. Note that these endpoints are not accessable and only here for reference purposes.


## AccountHeader [/AccountHeader]
A multipurpose object used by several endpoints and with multiple source tables depending on context. The object described below is generic. 

### AccountHeader [GET]
The account header object is derived from multiple locations of the database depending on the the value of AccountType. All are documented below.
<br /><br />
<strong>AccountType: C</strong>

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|AccountType|A Single Letter Denoting Account Type|`string`|1||`C`|
|AccountId|Account ID|`string`|11|||
|AccountDescription|Account Description|`string`|200|||
|EDICode|Account EDI Code|`string`|50|||
|Status|Account Status|`string`|1||`O` or `F`|

<br />
<strong>AccountType: N</strong>

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|AccountType|A Single Letter Denoting Account Type|`string`|1||`N`|
|AccountId|Account ID|`string`|11|||
|AccountDescription|Account Description|`string`|200|||
|EDICode|Account EDI Code|`string`|50|||
|Status|Account Status|`string`|1||`O` or `F`|

<br />
<strong>AccountType: K</strong>

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|AccountType|A Single Letter Denoting Account Type|`string`|1||`K`|
|AccountId|Account ID|`string`|11|||
|AccountDescription|Account Description|`string`|200|||
|EDICode|Account EDI Code|`string`|50|||
|Status|Account Status|`string`|1||`O` or `F`|

+ Response 200 (application/json; charset=utf-8)
+ Attributes (AccountHeader)

## Contract Currency [/ContractCurrency]
A multipurpose object used by several endpoints
### ContractCurrency [GET]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|CurrencyCode|Currency Code|`string`|3||Required|
|ConValContract|Contract Value Contract|`number`||||
|CostValContract|Cost Value Contract|`number`||||
|ComsnValContract|Commission Value Contract|`number`||||
|PolValContract|Polarisation Value Contract|`number`||||
|FOContract|F&O Contract|`number`||||
|FXContract|FX Contract|`number`||||
|MktValContract|Market Value Contract|`number`||||

+ Response 200 (application/json; charset=utf-8)
+ Attributes (ValuesInContractCcy)

## Functional Currency [/FunctionalCurrency]
A multipurpose object used by several endpoints
### FunctionalCurrency [GET]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|CurrencyCode|Currency Code|`string`|3||Required|
|ConValFunctional|Contract Value Functional|`number`||||
|CostValFunctional|Cost Value Functional|`number`||||
|ComsnValFunctional|Commission Value Functional|`number`||||
|PolValFunctional|Polarisation Value Functional|`number`||||
|FOFunctional|F&O Functional|`number`||||
|FXFunctional|FX Functional|`number`||||
|MktValFunctional|Market Value Functional|`number`||||

+ Response 200 (application/json; charset=utf-8)
+ Attributes (ValuesInFunctionalCcy)

## PnL Currency [/PnLCurrency]
A multipurpose object used by several endpoints
### PnLCurrency [GET]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|CurrencyCode|Currency Code|`string`|3||Required|
|ConValPnL|Contract Value PnL|`number`||||
|CostValPnL|Cost Value PnL|`number`||||
|ComsnValPnL|Commission Value PnL|`number`||||
|PolValPnL|Polarisation Value PnL|`number`||||
|FOPnL|F&O PnL|`number`||||
|FXPnL|FX PnL|`number`||||
|MktValPnL|Market Value PnL|`number`||||

+ Response 200 (application/json; charset=utf-8)
+ Attributes (ValuesInPnLCcy)

## User Account [/UserAccount]
A multipurpose object used by several endpoints
### User Account [GET]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|UserAccountId|User Account ID|`string`|3||Required|
|UserAccountName|User Account Name|`string`|255|||
|UserAccountDescription|User Account Description|`string`|40|||

+ Response 200 (application/json; charset=utf-8)
+ Attributes (UserAccount)

## WIP Account [/WipAccount]
A multipurpose object used by several endpoints
### WIP Account [GET]

|Property|Description|Type|Max Length|Notes|Constraint|
|--------|-----------|----|----------|-----|----------|
|WIPAccountId|WIP Account ID|`string`|11||Required|
|WIPAccountDescription|WIP Account Description|`string`|60|||
|WIPAccountType|WIP Account Type|`string`|1|||
|Status|Status|`string`|1||`O` or `F`|

+ Response 200 (application/json; charset=utf-8)
+ Attributes (WIPAccount)


# Data Structures

## 200 SuccessResponse (object)
+ Value: Success (string)

## 200 CreateResponse (object)
+ Value: Created (string)

## 200 UpdateResponse (object)
+ Value: Updated (string)

## 201 CreateResponse (object)
+ Value: Created (string)

## 400 BadRequestResponse (object)
+ Value: Bad Request

## 400 Response (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array [400 ErrorMessageDetail])

## 400 ErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5058 - Data : The mandatory field {fieldName} was missing in the request body.` (string)

## 400 ResponseDQS (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array [400 ErrorMessageDetailDQS])

## 400 ErrorMessageDetailDQS (object)
+ Severity: Error (string)
+ Message: `{fieldName} is not a field of type {fieldName}.` (string)

## 400 BadPropertyResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array[400 BadPropertyErrorMessageDetail])

## 400 BadPropertyErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5068 - API : The value sent in the querystring variable {Property} is not allowed.` (string)

## 400 BadReadResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (array[400 BadReadErrorMessageDetail])

## 400 BadReadErrorMessageDetail (object)
+ Severity: Error (string)
+ Message: `API5075 - API : The value sent in the querystring is not allowed.` (string)

## 400 ServiceResponse (object)
+ Response
    + Value: 400 Bad Request (string)
+ Messages (400 ServiceResponseDetail)

## 400 ServiceResponseDetail (object)
+ Severity: Error (string)
+ Messages: `API5058 - Data : The mandatory field {fieldName} was missing.` (string)

## 400 BadCertificateResponse (object)
+ Response
    + Value: 400 Failed (string)
+ Messages (400 BadCertificateResponseDetail)

## 400 BadCertificateResponseDetail (object)
+ Severity: Error (string)
+ Messages: `API5091 - API : There is no certificate/user for RequestId {RequestId}` (string)

## 400 StatusResponse (object)
+ Response
    + Value: 400 Failed (string)
+ Messages (400 StatusResponseDetail)

## 400 StatusResponseDetail (object)
+ Severity: Error (string)
+ Messages: `API5090 - API : The value {value} is not allowed for the field {FieldName}` (string)

## 400 WarningMessageDetail (object)
+ Severity: Warning (string)
+ Message: `API50xx - Data : The field {fieldName} was not found.` (string)

## 400 InfoMessageDetail (object)
+ Severity: Information (string)
+ Message: `API50xx - Data : Now create xyz.` (string)

## 404 NotFoundResponse (object)
+ Value: Not Found

## 404 ResponseNoRec (object)
+ Response
    + Value: 404 Not Found (string)
+ Messages (array[404 ErrorMessageDetailMessageNoRec])

## 404 ErrorMessageDetailMessageNoRec (object)
+ Severity: Warning (string)
+ Message: `API5068 - Data : No records found.` (string)

## 404 NotFound (object)
+ Severity: Error (string)
+ Message: `API5067 - API : The value {inputValue} does not exist.` (string)

## 404 DocumentIdResponse (object)
+ Response
    + Value: 404 Object not found (string)
+ Messages (array[404 ErrorMessageRequestIdMessage])

## 404 ErrorMessageDocumentIdMessage (object)
+ Severity: Error (string)
+ Message: `API5067 - API : The value {DocumentId} sent as the DocumentId does not exist.` (string)

## 404 Response (object)
+ Response
    + Value: 404 Object not found (string)
+ Messages (array[404 ErrorMessageDetailMessage])

## 404 ErrorMessageDetailMessage (object)
+ Severity: Warning (string)
+ Message: `API5084 - API : The value {TradingEntityId} sent as the TradingEntitiyId does not exist.` (string)

## 404 ResponseDQS (object)
+ Response
    + Value: 404 Not found (string)
+ Messages (array[404 ErrorMessageDetailMessageDQS])

## 404 ErrorMessageDetailMessageDQS (object)
+ Severity: Warning (string)
+ Message: `Invalid trading entities specified: {tradingEntity}.` (string)

## 404 RequestIdResponse (object)
+ Response
    + Value: 404 Object not found (string)
+ Messages (array[404 ErrorMessageRequestIdMessage])

## 404 ErrorMessageRequestIdMessage (object)
+ Severity: Error (string)
+ Message: `API5067 - API : The value {RequestId} sent as the RequestId does not exist.` (string)


## 404 ServiceResponse (object)
+ Response
    + Value: 404 Object not found (string)
+ Messages (404 ServiceResponseDetail)

## 404 ServiceResponseDetail (object)
+ Severity: Warning (string)
+ Message: `API5067 - API : The value {ServiceName} does not exist.` (string)

## accessToken (object)
+ Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1bmlxdWVfbmFtZSI6ImRlZXBhayIsInN1YiI6ImRlZXBhayIsInJvbGUiOlsiNzk5YjhhNDEtYWI0ZS00MTBhLWI5MTktYzU3ZWFlMmFlMDI5IiwiZGVlcGFrIiwiQVNQLk5FVCBJZGVudGl0eSIsIjViNDE4ODE2LTI3ZjQtNGRlOC1iNmMyLTJlZTcxNjI3ZmJmYyIsIkFkbWluIiwiU3VwZXJBZG1pbiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMjciLCJhdWQiOiI4MjkzNjk0MjJmNzA0NTIzODUxZDk4NTU2YjZkNTQyYiIsImV4cCI6MTQ1OTQzMjk0MSwibmJmIjoxNDU5NDMxMTQxfQ.JgPGxt0Ok5baKx0YMXlO6D9kUYrCWM-Kma9b9iMW8tg (string)

## AccountHeader (object)
+ AccountType: C (string)
+ AccountId: 00040444.P (string)
+ AccountDescription: Nigeria Trading Dept (string)
+ EDICode: ABC1234 (string)
+ Status: F (string)

## AccountHeaderC (object)
+ AccountType: C (string)
+ AccountId: 00040444.P (string)
+ AccountDescription: Nigeria Trading Dept (string)
+ EDICode: ABC1234 (string)
+ Status: F (string)

## AccountHeaderN (object)
+ AccountType: N (string)
+ AccountId: 0510.1000 (string)
+ AccountDescription: Computer Equipment | Cost (string)
+ EDICode: 1234 (string)
+ Status: O (string)

## AccountHeaderK (object)
+ AccountType: K    (string)
+ AccountId: 5100.MEP (string)
+ AccountDescription: Bauche Account Provisions (string)
+ EDICode: 1234 (string)
+ Status: O (string)

## ArchiveDocument (object)
+ Path: `JT\\CASHDOCS\\TEST.TXT` (string)

## CommodityValueList (object)
+ CommodityFullCode: CHE||CASO||47||QWE||RTY (string)
+ PnLCurrency (array [ValuesInPnLCcy])
+ ContractCurrency (array [ValuesInContractCcy])
+ FunctionalCurrency (array [ValuesInFunctionalCcy])

## ContractTermValueList (object)
+ ContractTermCode: DEL (string)
+ PnLCurrency (array [ValuesInPnLCcy])
+ ContractCurrency (array [ValuesInContractCcy])
+ FunctionalCurrency (array [ValuesInFunctionalCcy])

## ContractTermPortValueList (object)
+ ContractTermPortCode: LIV (string)
+ PnLCurrency (array [ValuesInPnLCcy])
+ ContractCurrency (array [ValuesInContractCcy])
+ FunctionalCurrency (array [ValuesInFunctionalCcy])

## CounterpartyValueList (object)
+ CounterpartyCode: ABANI.P (string)
+ PnLCurrency (array [ValuesInPnLCcy])
+ ContractCurrency (array [ValuesInContractCcy])
+ FunctionalCurrency (array [ValuesInFunctionalCcy])

## Country (object)
+ CountryId: GB (string)
+ CountryDescription: Great Britain (string)


## DataFactoryExport (object)
+ Request: `<?xml version="1.0"?><PackageInput DFname="TestPackage" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://itashelp.hivedome.net/media/inpTestPackage.xsd"> <TradingEntityCode>xx</TradingEntityCode><CutOffDate>2018-04-30</CutOffDate></PackageInput>` (string)


## DepartmentCreate (object)
+ DepartmentId : ABCD (string)
+ DepartmentDescription : ABCD Dep (string)

## DepartmentUpdate (object)
+ DepartmentId : ABCD (string)
+ DepartmentDescription : Department ABCD (string)

## DepartmentValueList (object)
+ DepartmentCode: NAD (string)
+ PnLCurrency (array [ValuesInPnLCcy])
+ ContractCurrency (array [ValuesInContractCcy])
+ FunctionalCurrency (array [ValuesInFunctionalCcy])


## DocmanDocumentId (object)
+ DocmanDocumentId: 12345 (number)

## DQSDepartments (object)
+ TradingEntityId: jt (string)
+ DepartmentId: 1111 (string)
+ DepartmentDescription: Department 1111 (string)
+ NominalCategory (NominalCategory)
+ Country (Country)
+ EDICode: EDI1234 (string)
+ Status: O (string)

## IndexDocument (object)
+ Name: `20180113_ADIL01_WHS.RTF` (string)
+ TradingEntityId: JT (string)
+ DocumentType: TRADEDOCS (string)
+ CounterpartyId: `NEWACC30.P` (string)
+ ContractId: `P00001.000` (string)
+ DocumentRef: PI1574747 (string)
+ WIPAccountId: `0001.000` (string)
+ PhysicalPath: `\\\\hivedome-fs01\\itas\\Comp\\DroppedFiles\\JT\\TRADEDOCS\\ITAS_NG.20180220.log` (string)
+ IsPhysicalPathEncrypted: false (boolean)

## IndexId (object)
+ IndexId: 100 (number)

## JobId (object)
+ JobRef: Job1 (string)

## NominalCategory (object)
+ NominalCategoryId: AA (string)
+ NominalCategoryDescription: AA Trading (string)
+ NominalGroup: BB (string)

## Pagination (object)
+ Total: 250 (number) - total number of records available
+ Top: 200 (number) - max number returned per message 
+ Skip: 100 (number) - number of records skipped
+ Returned: 150 (number) - actual number returned

## PaymentTermValueList (object)
+ PaymentTermCode: INV30 (string)
+ PnLCurrency (array [ValuesInPnLCcy])
+ ContractCurrency (array [ValuesInContractCcy])
+ FunctionalCurrency (array [ValuesInFunctionalCcy])

## PhysicalTradeValRequest (object)
+ TradingEntityId: JT,DT (array[string])
+ RateOfExchangeDate: 20161028 (number)
+ TableExtension: `_20161032` (string)
+ IncludeFOPnLAndFOContractValuations: false (boolean)

## PhysicalTradeValTradingEntityRequest (object)
+ RateOfExchangeDate: 20161028 (number)
+ TableExtension: `_20161032` (string)
+ IncludeFOPnLAndFOContractValuations: false (boolean)

## PhysicalTradeValResponse (object)
+ RequestId: `a123a456-7891-23a4-a567-8a9a10aaa123` (string)

## PhysicalTradeValuesResults (object)
+ ContractId: P00004.000 (string)
+ TradingEntityId: JT (string)
+ PnLCurrency (ValuesInPnLCcy)
+ ContractCurrency (ValuesInContractCcy)
+ FunctionalCurrency (ValuesInFunctionalCcy) 

## PhysicalTradeValuesResultsSum (object)
+ CounterpartyList (array [CounterpartyValueList])
+ CommodityList (array [CommodityValueList])
+ TraderList (array [TraderValueList])
+ DepartmentList (array [DepartmentValueList])
+ PaymentTermList (array [PaymentTermValueList])
+ ContractTermList (array [ContractTermValueList])
+ ContractTermPortList (array [ContractTermPortValueList])
+ ShipmentStatusList (array [ShipmentStatusValueList])
+ TradingEntityList (array [TradingEntityValueList])

## RequiredFields (array)
+ ContractId
+ DocumentReference

## ResultsMessage (object)
+ RequestId: `a123a456-7891-23a4-a567-8a9a10aaa123` (string)
+ RequestTime: `2016-07-01T12:20:30Z` (string)
+ RequestStatus: Completed (string)

## ResultsMessageComplete (object)
+ RequestId: `a123a456-7891-23a4-a567-8a9a10aaa123` (string)
+ RequestTime: `2016-07-01T12:20:30Z` (string)
+ RequestStatus: Completed (string)
+ RequestCompleteTime: `2016-07-01T12:22:30Z` (string)

## ReportFactoryExport (object)
+ Request: `<?xml version="1.0"?><ITASReportInput RFname="TestReport" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://itashelp.hivedome.net/media/inpTestReport.xsd"><TradingEntityCode>xx</TradingEntityCode><AccountInitials>zz</AccountInitials><DataSourceConnectionString>abcdefghijklmnopqrstuvwxyz</DataSourceConnectionString><OutputSchemaName>TestSchema</OutputSchemaName><OutputSchemaVersion>1</OutputSchemaVersion><OutputSchemaAddress>https://itashelp.hivedome.net/media/outTestReport.xsd</OutputSchemaAddress><OutputStyle></OutputStyle><OutputFolder></OutputFolder><OutputFilename></OutputFilename><SilentMode>true</SilentMode><DbDate>0</DbDate><ReportType>Standard Report</ReportType></ITASReportInput>` (string)

## ShipmentStatusValueList (object)
+ ShipmentStatusCode: D (string)
+ PnLCurrency (array [ValuesInPnLCcy])
+ ContractCurrency (array [ValuesInContractCcy])
+ FunctionalCurrency (array [ValuesInFunctionalCcy])

## TraderValueList (object)
+ TraderCode: JRH (string)
+ PnLCurrency (array [ValuesInPnLCcy])
+ ContractCurrency (array [ValuesInContractCcy])
+ FunctionalCurrency (array [ValuesInFunctionalCcy])

## TradingEntityValueList (object)
+ TradingEntityId: JT (string)
+ PnLCurrency (array [ValuesInPnLCcy])
+ ContractCurrency (array [ValuesInContractCcy])
+ FunctionalCurrency (array [ValuesInFunctionalCcy])

## UserAccount (object)
+ UserAccountId: JS (string)
+ UserAccountName: JSMITH (string)
+ UserAccountDescription: John Smith (string) 

## ValuesInContractCcy (object)
+ CurrencyCode: USD (string)
+ ConValContract: 4050 (number)
+ CostValContract: 200 (number)
+ ComsnValContract: 3000 (number)
+ PolValContract: 100 (number)
+ FOContract: 3750 (number)
+ FXContract: 3900 (number)
+ MktValContract: 4800 (number)

## ValuesInFunctionalCcy (object)
+ CurrencyCode: GBP (string)
+ ConValFunctional: 3500 (number)
+ CostValFunctional: 900 (number)
+ ComsnValFunctional: 1200 (number)
+ PolValFunctional: 1700 (number)
+ FOFunctional: 2500 (number)
+ FXFunctional: 2900 (number)
+ MktValFunctional: 3600 (number)

## ValuesInPnLCcy (object)
+ CurrencyCode: GBP (string)
+ ConValPnL: 3500 (number)
+ CostValPnL: 900 (number)
+ ComsnValPnL: 1200 (number)
+ PolValPnL: 1700 (number)
+ FOPnL: 2500 (number)
+ FXPnL: 2900 (number)
+ MktValPnL: 3600 (number)

## WIPAccount (object)
+ WIPAccountId: 1111.MEP (required, string)
+ WIPAccountDescription: `MEPACCRUE - East Africa Dept` (string)
+ WIPAccountType: M (string)
+ Status: F (string)